### ISSUE TITLE
Enabling_02 - hj_01_03_06_03 - EN 2 - ex. Task 6 Step 3 - Hindi font not connecting

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#324]

**Comment by sdub** [comment]
Also need the Hindi font a few sizes larger.

**Comment by sueykim** [comment]
Fixed and updated on Github

**Comment by sdub** [comment]
Hindi font not connecting yet in text boxes and still too small, please update. Thank you!

**Comment by sdub** [comment]
Font size good now but letters are still not connecting, please check again.

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Looks great, thanks!
